#! /bin/sh

sxhkd &
pidof compton && killall compton
wal -R -o $HOME/.config/dunst/launchdunst.sh

#bspc monitor -d 一 二 三 四 五
bspc monitor -d I II III IV V
#VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          20

bspc config top_padding			10
bspc config bottom_padding		10
bspc config right_padding		10
bspc config left_padding		10

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox state=floating center=true desktop='^2' rectangle=600x400+10+10
#bspc rule -a feh state=floating

bspc config normal_border_color		'#be4678'
bspc config active_border_color		'#be4678'
bspc config focused_border_color	'#FFFFFF'

compton &
feh --bg-fill $HOME/.config/wall.jpg
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr
xmodmap $HOME/.Xmodmap
xcape -e 'Control_L=Escape'
#xcape -e 'Super_L=Super_L|Space'
